import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Messenger from "../components/messenger"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FB Tester App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Messenger />
        <form method="POST" action="/api/profile">
          <h3>Setup profile API :</h3>
          <button type="submit">Submit</button>
        </form>

      </main>
      {/* <main className={styles.main}>
        <form action="/api/message" method="POST">
          <label htmlFor="message">
            Message:
            <textarea id="message" name="message" type="text" />
          </label>
          <input type="submit" value="Submit" />
        </form>
      </main> */}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
